version: '3'
    
services:
  db:
    container_name: houm_test_db
    image: postgres
    environment:
      - POSTGRES_DB=houm_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
       - "5435:5432"
  web:
    container_name: houm_test
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./ :/opt/app/
    ports:
      - "8002:8002"
    depends_on:
      - db