# Generated by Django 4.0.2 on 2022-02-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('created', models.DateField(auto_now_add=True)),
                ('coordinates', models.JSONField(default=dict)),
                ('houmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property', to='houmer.houmer')),
            ],
        ),
    ]
