# Generated by Django 4.0.2 on 2022-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0002_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houmer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
