# Generated by Django 4.0.2 on 2022-02-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0003_alter_houmer_created_alter_property_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('houmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='houmer.houmer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='houmer.property')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_coordinates', models.JSONField(default=dict)),
                ('houmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move', to='houmer.houmer')),
                ('property_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move', to='houmer.property')),
            ],
        ),
    ]
